### ISSUE TITLE
Readme example uses shorthand with full word

### ISSUE THREAD

**Issue by PonchoPowers** [dotmake-build/command-line#19]
> Both POSIX and Windows prefix conventions are supported. When manually setting a name (overriding decorated property's name), you should specify the option name including the prefix (e.g. --option, -option or /option)

Should read

> Both POSIX and Windows prefix conventions are supported. When manually setting a name (overriding decorated property's name), you should specify the option name including the prefix (e.g. --option, -o or /option)

As - is shorthand and -- is longhand.

So -o is correct and -option means -o -p -t -i -o -n, which is not what you meant.

**Comment by calacayir** [comment]
Ok updated docs:

> Both POSIX and Windows prefix conventions are supported. When manually setting a name (overriding decorated property's name), you should specify the option name including the prefix (e.g. --option, -o, -option or /option).
>
> Bundling of single-character options are supported, also known as stacking. Bundled options are single-character option aliases specified together after a single hyphen prefix. For example if you have options "-a", "-b" and "-c", you can bundle them like "-abc". Only the last option can specify an argument. Note that if you have an explicit option named "-abc" then it will win over bundled options.
