### ISSUE TITLE
Inheriting options does not work

### ISSUE THREAD

**Issue by PatrickBig** [dotmake-build/command-line#4]
I have some commands that have some shared options.

Eg: I have 5 commands that all require a `--username` and `--password` option.

I would expect that I could do something like this:

```csharp
public abstract class CredentialCommandBase
{
    [CliOption(Description = "Username of the identity performing the command")]
    public string Username { get; set; }

    [CliOption(Description = "Password of the identity performing the command")]
    public string Password { get; set; }
}
```

Then implement thusly

```csharp
[CliCommand]
public MyCommand : CredentialCommandBase
{
    public void Run(InvocationContext context)
    {
        Console.WriteLine("I am " + Username);
    }
}
```

Compiles just fine, but when ran you will not get any help information, nor can you set the Username property.

I should also add that it would be nice if it could pickup annotations from interfaces to generate as well.

**Comment by calacayir** [comment]
You are right, this feature is needed. I will be added shortly.

> I should also add that it would be nice if it could pickup annotations from interfaces to generate as well.

I guess this could be also done, as interfaces allow properties.
