### ISSUE TITLE
ServiceProvider support

### ISSUE THREAD

**Issue by mcolebiltd** [dotmake-build/command-line#5]
I'd like to inject services into commands. Is this currently possible or do I need to pass the configured ServiceProvider into the commands as an argument?

**Comment by calacayir** [comment]
This is now supported with v1.6.2:

- Added dependency injection support. When the source generator detects that your project has reference
  to `Microsoft.Extensions.DependencyInjection`, it will generate extension methods for supporting dependency injection.
  For example, you can now add your services with the extension method `Cli.Ext.ConfigureServices`:

  ```c#
  using DotMake.CommandLine;
  using Microsoft.Extensions.DependencyInjection;
  
  Cli.Ext.ConfigureServices(services =>
  {
      services.AddTransient<TransientClass>();
      services.AddScoped<ScopedClass>();
      services.AddSingleton<SingletonClass>();
  });
  
  Cli.Run<RootCliCommand>();
  ```
  Then let them be injected to your command class automatically by providing a constructor with the required services:
  ```c#
  [CliCommand(Description = "A root cli command with dependency injection")]
  public class RootCliCommand
  {
      private readonly TransientClass transientDisposable;
      private readonly ScopedClass scopedDisposable;
      private readonly SingletonClass singletonDisposable;
  
      public RootCliCommand(
          TransientClass transientDisposable,
          ScopedClass scopedDisposable,
          SingletonClass singletonDisposable
      )
      {
          this.transientDisposable = transientDisposable;
          this.scopedDisposable = scopedDisposable;
          this.singletonDisposable = singletonDisposable;
      }
  
      [CliOption(Description = "Description for Option1")]
      public string Option1 { get; set; } = "DefaultForOption1";
  
      [CliArgument(Description = "Description for Argument1")]
      public string Argument1 { get; set; }
  
      public void Run()
      {
          Console.WriteLine($@"Handler for '{GetType().FullName}' is run:");
          Console.WriteLine($@"Value for {nameof(Option1)} property is '{Option1}'");
          Console.WriteLine($@"Value for {nameof(Argument1)} property is '{Argument1}'");
          Console.WriteLine();
  
          Console.WriteLine($"Instance for {transientDisposable.Name} is available");
          Console.WriteLine($"Instance for {scopedDisposable.Name} is available");
          Console.WriteLine($"Instance for {singletonDisposable.Name} is available");
          Console.WriteLine();
      }
  }
  
  public sealed class TransientClass : IDisposable
  {
      public string Name => nameof(TransientClass);
  
      public void Dispose() => Console.WriteLine($"{nameof(TransientClass)}.Dispose()");
  }
  
  public sealed class ScopedClass : IDisposable
  {
      public string Name => nameof(ScopedClass);
  
      public void Dispose() => Console.WriteLine($"{nameof(ScopedClass)}.Dispose()");
  }
  
  public sealed class SingletonClass : IDisposable
  {
      public string Name => nameof(SingletonClass);
  
      public void Dispose() => Console.WriteLine($"{nameof(SingletonClass)}.Dispose()");
  }
  ```

**Comment by mcolebiltd** [comment]
Fantastic. Thank you!

**Comment by pdegenhardt** [comment]
This is using ServiceProvider, rather than IServiceProvider. Is it possible to use the latter? We can then utilise other containers such as Autofac.

**Comment by calacayir** [comment]
Hi,
This is now possible with v1.8.1:

- Added support for other dependency injection containers (e.g. Autofac) when
  only `Microsoft.Extensions.DependencyInjection.Abstractions` package (version >= 2.1.1) is added to the project.
  You can set your custom service provider with the extension method `Cli.Ext.SetServiceProvider`.
  In previous version, this method already existed but accepted a `ServiceProvider` parameter, instead of
  `IServiceProvider` parameter which allows 3rd party implementations other than the default one in `Microsoft.Extensions.DependencyInjection`.

  ```c#
  using DotMake.CommandLine;
  using Autofac.Core;
  using Autofac.Core.Registration;
  
  var cb = new ContainerBuilder();
  cb.RegisterType<object>();
  var container = cb.Build();
  
  Cli.Ext.SetServiceProvider(container);
  
  Cli.Run<RootCliCommand>();
  ```

- Reduced minimum version requirement for `Microsoft.Extensions.DependencyInjection` from `6.0.0` to `2.1.1`
  so that you don't need to update it in legacy projects. Added `Cli.Ext.GetServiceCollection` and
  `Cli.Ext.GetServiceProviderOrDefault` extension methods.

**Comment by pdegenhardt** [comment]
That is awesome! Thanks @calacayir !
