### ISSUE TITLE
Generated code triggers CS1591 when generating documentation file is turned on

### ISSUE THREAD

**Issue by PatrickBig** [dotmake-build/command-line#6]
The generated files Eg: `MyCommandBuilder-hiuadwahu.g.cs` will generate the warning CS1591 when the project has the GenerateDocumentationFile property set to true.

There is a tag in the header of these files `<auto-generated />`, but this only helps in some scenarios like StyleCop.

Consider adding `#pragma warning disable CS1591` to each generated file as well to prevent this.

**Comment by calacayir** [comment]
Good catch, thanks for reporting. This is now fixed with v1.6.4.

**Comment by PatrickBig** [comment]
Adding documentation is even better than ignoring the warning. Good fix :)
